import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';
import { Unit } from '../../units/entities/unit.entity';
import { Bank } from '../../banks/entities/bank.entity';
import { Color } from '../../colors/entities/color.entity';
import { Location } from '../../location/entities/location.entity';
import { Supplier } from '../../suppliers/entities/supplier.entity';
import { User } from '../../users/entities/user.entity';
import { RawMaterial } from '../../raw-materials/entities/raw-material.entity';
import * as bcrypt from 'bcrypt';

export default class MainSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<void> {
    console.log('🌱 Iniciando seed...');

    // ─── Unidades ───────────────────────────────────────────
    const unitRepo = dataSource.getRepository(Unit);
    const units = await unitRepo.save(
      unitRepo.create([
        { description: 'Metro (m)' },
        { description: 'Quilograma (kg)' },
        { description: 'Unidade (un)' },
        { description: 'Litro (L)' },
        { description: 'Par' },
        { description: 'Rolo' },
        { description: 'Peça' },
        { description: 'Centímetro (cm)' },
        { description: 'Grama (g)' },
        { description: 'Mililitro (mL)' },
        { description: 'Jogo' },
        { description: 'Caixa' },
        { description: 'Pacote' },
        { description: 'Dúzia' },
      ]),
    );
    console.log(`✅ ${units.length} unidades criadas`);

    // ─── Bancos ─────────────────────────────────────────────
    const bankRepo = dataSource.getRepository(Bank);
    const banks = await bankRepo.save(
      bankRepo.create([
        { description: 'Banco do Brasil' },
        { description: 'Bradesco' },
        { description: 'Itaú' },
        { description: 'Caixa Econômica Federal' },
        { description: 'Santander' },
        { description: 'Nubank' },
        { description: 'Inter' },
        { description: 'Sicoob' },
        { description: 'Sicredi' },
        { description: 'Safra' },
      ]),
    );
    console.log(`✅ ${banks.length} bancos criados`);

    // ─── Cores ──────────────────────────────────────────────
    const colorRepo = dataSource.getRepository(Color);
    const colors = await colorRepo.save(
      colorRepo.create([
        { description: 'Branco', supplierDescription: 'Branco Neve' },
        { description: 'Preto', supplierDescription: 'Preto Intenso' },
        { description: 'Azul', supplierDescription: 'Azul Royal' },
        { description: 'Vermelho', supplierDescription: 'Vermelho Vivo' },
        { description: 'Verde', supplierDescription: 'Verde Militar' },
        { description: 'Amarelo', supplierDescription: 'Amarelo Ouro' },
        { description: 'Cinza', supplierDescription: 'Cinza Mescla' },
        { description: 'Bege', supplierDescription: 'Bege Areia' },
        { description: 'Marrom', supplierDescription: 'Marrom Tabaco' },
        { description: 'Rosa', supplierDescription: 'Rosa Claro' },
        { description: 'Laranja', supplierDescription: 'Laranja Cítrico' },
        { description: 'Lilás', supplierDescription: 'Lilás Suave' },
        { description: 'Turquesa', supplierDescription: 'Turquesa Tropical' },
        { description: 'Vinho', supplierDescription: 'Vinho Bordô' },
        { description: 'Off-White', supplierDescription: 'Off-White Cru' },
        { description: 'Nude', supplierDescription: 'Nude Pele' },
        { description: 'Coral', supplierDescription: 'Coral Vivo' },
        { description: 'Mostarda', supplierDescription: 'Mostarda Queimado' },
        { description: 'Cáqui', supplierDescription: 'Cáqui Militar' },
        { description: 'Navy', supplierDescription: 'Azul Marinho' },
      ]),
    );
    console.log(`✅ ${colors.length} cores criadas`);

    // ─── Localizações ───────────────────────────────────────
    const locationRepo = dataSource.getRepository(Location);
    const locations = await locationRepo.save(
      locationRepo.create([
        { location: 'Almoxarifado A - Prateleira 1' },
        { location: 'Almoxarifado A - Prateleira 2' },
        { location: 'Almoxarifado A - Prateleira 3' },
        { location: 'Almoxarifado B - Prateleira 1' },
        { location: 'Almoxarifado B - Prateleira 2' },
        { location: 'Almoxarifado B - Prateleira 3' },
        { location: 'Galpão Central' },
        { location: 'Galpão Central - Área de Corte' },
        { location: 'Depósito Externo' },
        { location: 'Sala de Costura' },
        { location: 'Sala de Acabamento' },
        { location: 'Expedição' },
      ]),
    );
    console.log(`✅ ${locations.length} localizações criadas`);

    // ─── Fornecedores ───────────────────────────────────────
    const supplierRepo = dataSource.getRepository(Supplier);
    const suppliers = await supplierRepo.save(
      supplierRepo.create([
        {
          tradeName: 'Tecidos Brasil',
          corporateName: 'Tecidos Brasil Ltda',
          cnpj: '11.222.333/0001-44',
          stateRegistration: '123.456.789.000',
          address: 'Rua das Indústrias, 100',
          complement: 'Galpão 3',
          city: 'São Paulo',
          state: 'SP',
          postalCode: '01000-000',
          country: 'Brasil',
          contact: '(11) 3000-0001',
          commercialContact: '(11) 3000-0002',
          bank: banks[0],
          bankAgency: '1234-5',
          checkingAccount: '00012345-6',
        },
        {
          tradeName: 'Aviamentos Central',
          corporateName: 'Aviamentos Central S.A.',
          cnpj: '22.333.444/0001-55',
          stateRegistration: '987.654.321.000',
          address: 'Av. Paulista, 2000',
          complement: 'Sala 501',
          city: 'São Paulo',
          state: 'SP',
          postalCode: '01310-200',
          country: 'Brasil',
          contact: '(11) 4000-0001',
          bank: banks[1],
          bankAgency: '5678-9',
          checkingAccount: '00098765-4',
        },
        {
          tradeName: 'Linhas & Fios',
          corporateName: 'Linhas e Fios Indústria Ltda',
          cnpj: '33.444.555/0001-66',
          stateRegistration: '111.222.333.000',
          address: 'Rua dos Tecelões, 50',
          complement: 'Bloco B',
          city: 'Blumenau',
          state: 'SC',
          postalCode: '89010-100',
          country: 'Brasil',
          contact: '(47) 3000-0001',
          bank: banks[2],
          bankAgency: '1111-2',
          checkingAccount: '00055555-7',
        },
        {
          tradeName: 'Malhas do Sul',
          corporateName: 'Malhas do Sul Indústria e Comércio Ltda',
          cnpj: '44.555.666/0001-77',
          stateRegistration: '222.333.444.000',
          address: 'Rua XV de Novembro, 300',
          complement: 'Pavilhão 2',
          city: 'Caxias do Sul',
          state: 'RS',
          postalCode: '95010-000',
          country: 'Brasil',
          contact: '(54) 3000-0001',
          commercialContact: '(54) 3000-0002',
          bank: banks[3],
          bankAgency: '2222-3',
          checkingAccount: '00066666-8',
        },
        {
          tradeName: 'Químicos Têxteis',
          corporateName: 'Químicos Têxteis do Nordeste S.A.',
          cnpj: '55.666.777/0001-88',
          stateRegistration: '333.444.555.000',
          address: 'Av. Industrial, 1500',
          complement: 'Bloco A',
          city: 'Recife',
          state: 'PE',
          postalCode: '50000-000',
          country: 'Brasil',
          contact: '(81) 3000-0001',
          bank: banks[4],
          bankAgency: '3333-4',
          checkingAccount: '00077777-9',
        },
        {
          tradeName: 'Etiquetas Express',
          corporateName: 'Etiquetas Express Ltda',
          cnpj: '66.777.888/0001-99',
          stateRegistration: '444.555.666.000',
          address: 'Rua da Estampa, 80',
          complement: 'Sala 12',
          city: 'Belo Horizonte',
          state: 'MG',
          postalCode: '30130-000',
          country: 'Brasil',
          contact: '(31) 3000-0001',
          commercialContact: '(31) 3000-0002',
          bank: banks[5],
          bankAgency: '4444-5',
          checkingAccount: '00088888-0',
        },
      ]),
    );
    console.log(`✅ ${suppliers.length} fornecedores criados`);

    // ─── Usuários ─────────────────────────────────────────────
    const userRepo = dataSource.getRepository(User);
    const hashedPassword = await bcrypt.hash('admin123', 10);
    const users = await userRepo.save(
      userRepo.create([
        {
          name: 'Administrador',
          login: 'admin',
          password: hashedPassword,
        },
        {
          name: 'Maria Silva',
          login: 'maria.silva',
          password: await bcrypt.hash('maria123', 10),
        },
        {
          name: 'João Pereira',
          login: 'joao.pereira',
          password: await bcrypt.hash('joao123', 10),
        },
      ]),
    );
    console.log(`✅ ${users.length} usuários criados`);

    // ─── Matérias-Primas ────────────────────────────────────
    const rawMaterialRepo = dataSource.getRepository(RawMaterial);
    const rawMaterials = await rawMaterialRepo.save(
      rawMaterialRepo.create([
        {
          code: 'MP-001',
          description: 'Tecido de Algodão Branco',
          unitId: units[0].id,
          value: 25.5,
          stock: 500,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[0].id,
          width: 1.5,
          grammage: 200,
          locationId: locations[0].id,
          composition: '100% Algodão',
          ncm: '5208.11.00',
          type: 'Tecido',
          status: 'Ativo',
        },
        {
          code: 'MP-002',
          description: 'Tecido Poliéster Preto',
          unitId: units[0].id,
          value: 18.9,
          stock: 320,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[1].id,
          width: 1.4,
          grammage: 180,
          locationId: locations[0].id,
          composition: '100% Poliéster',
          ncm: '5407.52.00',
          type: 'Tecido',
          status: 'Ativo',
        },
        {
          code: 'MP-003',
          description: 'Zíper Nylon 20cm Azul',
          unitId: units[2].id,
          value: 1.2,
          stock: 2000,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[2].id,
          locationId: locations[3].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-004',
          description: 'Botão de Madeira 15mm',
          unitId: units[2].id,
          value: 0.35,
          stock: 5000,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[8].id,
          locationId: locations[3].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-005',
          description: 'Linha de Costura Branca',
          unitId: units[5].id,
          value: 8.5,
          stock: 150,
          supplierId: suppliers[2].id as unknown as number,
          colorId: colors[0].id,
          locationId: locations[4].id,
          type: 'Linha',
          status: 'Ativo',
        },
        {
          code: 'MP-006',
          description: 'Elástico 3cm Branco',
          unitId: units[0].id,
          value: 3.2,
          stock: 800,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[0].id,
          width: 0.03,
          locationId: locations[5].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-007',
          description: 'Entretela Termocolante',
          unitId: units[0].id,
          value: 12.0,
          stock: 200,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[0].id,
          width: 0.9,
          grammage: 40,
          locationId: locations[6].id,
          composition: '100% Poliéster',
          type: 'Tecido',
          status: 'Ativo',
        },
        {
          code: 'MP-008',
          description: 'Malha Jersey Cinza Mescla',
          unitId: units[0].id,
          value: 32.0,
          stock: 450,
          supplierId: suppliers[3].id as unknown as number,
          colorId: colors[6].id,
          width: 1.8,
          grammage: 160,
          locationId: locations[0].id,
          composition: '95% Algodão, 5% Elastano',
          ncm: '6006.22.00',
          type: 'Malha',
          status: 'Ativo',
        },
        {
          code: 'MP-009',
          description: 'Malha Ribana Preta',
          unitId: units[0].id,
          value: 28.0,
          stock: 120,
          supplierId: suppliers[3].id as unknown as number,
          colorId: colors[1].id,
          width: 0.8,
          grammage: 250,
          locationId: locations[1].id,
          composition: '100% Algodão',
          ncm: '6006.21.00',
          type: 'Malha',
          status: 'Ativo',
        },
        {
          code: 'MP-010',
          description: 'Tecido Jeans Índigo',
          unitId: units[0].id,
          value: 42.0,
          stock: 280,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[19].id,
          width: 1.5,
          grammage: 340,
          locationId: locations[0].id,
          composition: '98% Algodão, 2% Elastano',
          ncm: '5209.42.00',
          type: 'Tecido',
          status: 'Ativo',
        },
        {
          code: 'MP-011',
          description: 'Linha de Costura Preta',
          unitId: units[5].id,
          value: 8.5,
          stock: 180,
          supplierId: suppliers[2].id as unknown as number,
          colorId: colors[1].id,
          locationId: locations[4].id,
          type: 'Linha',
          status: 'Ativo',
        },
        {
          code: 'MP-012',
          description: 'Zíper Metal 15cm Preto',
          unitId: units[2].id,
          value: 2.8,
          stock: 1500,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[1].id,
          locationId: locations[3].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-013',
          description: 'Botão de Pressão 12mm Prata',
          unitId: units[2].id,
          value: 0.55,
          stock: 3000,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[6].id,
          locationId: locations[3].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-014',
          description: 'Fita de Viés Bege 2,5cm',
          unitId: units[0].id,
          value: 1.8,
          stock: 600,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[7].id,
          width: 0.025,
          locationId: locations[5].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-015',
          description: 'Tecido Sarja Verde Militar',
          unitId: units[0].id,
          value: 29.5,
          stock: 150,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[4].id,
          width: 1.5,
          grammage: 240,
          locationId: locations[1].id,
          composition: '100% Algodão',
          ncm: '5208.33.00',
          type: 'Tecido',
          status: 'Ativo',
        },
        {
          code: 'MP-016',
          description: 'Renda Guipure Branca',
          unitId: units[0].id,
          value: 65.0,
          stock: 80,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[0].id,
          width: 1.2,
          grammage: 90,
          locationId: locations[2].id,
          composition: '100% Poliéster',
          ncm: '5804.21.00',
          type: 'Renda',
          status: 'Ativo',
        },
        {
          code: 'MP-017',
          description: 'Forro Acetinado Vermelho',
          unitId: units[0].id,
          value: 14.5,
          stock: 220,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[3].id,
          width: 1.4,
          grammage: 70,
          locationId: locations[6].id,
          composition: '100% Poliéster',
          ncm: '5407.42.00',
          type: 'Forro',
          status: 'Ativo',
        },
        {
          code: 'MP-018',
          description: 'Colchete de Gancho Nº 3',
          unitId: units[12].id,
          value: 4.5,
          stock: 400,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[1].id,
          locationId: locations[3].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-019',
          description: 'Tinta para Serigrafia Amarela',
          unitId: units[3].id,
          value: 55.0,
          stock: 25,
          supplierId: suppliers[4].id as unknown as number,
          colorId: colors[5].id,
          locationId: locations[8].id,
          type: 'Tinta',
          status: 'Ativo',
          observation: 'Armazenar em local fresco e arejado',
        },
        {
          code: 'MP-020',
          description: 'Etiqueta de Composição Impressa',
          unitId: units[13].id,
          value: 18.0,
          stock: 100,
          supplierId: suppliers[5].id as unknown as number,
          colorId: colors[0].id,
          locationId: locations[9].id,
          type: 'Etiqueta',
          status: 'Ativo',
        },
        {
          code: 'MP-021',
          description: 'Moleton Flanelado Cinza',
          unitId: units[0].id,
          value: 48.0,
          stock: 180,
          supplierId: suppliers[3].id as unknown as number,
          colorId: colors[6].id,
          width: 1.6,
          grammage: 380,
          locationId: locations[6].id,
          composition: '80% Algodão, 20% Poliéster',
          ncm: '6006.24.00',
          type: 'Malha',
          status: 'Ativo',
        },
        {
          code: 'MP-022',
          description: 'Ilhós Nº 54 Ouro Velho',
          unitId: units[11].id,
          value: 12.0,
          stock: 50,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[8].id,
          locationId: locations[5].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-023',
          description: 'Tecido Tricoline Rosa',
          unitId: units[0].id,
          value: 22.0,
          stock: 300,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[9].id,
          width: 1.5,
          grammage: 130,
          locationId: locations[1].id,
          composition: '100% Algodão',
          ncm: '5208.31.00',
          type: 'Tecido',
          status: 'Ativo',
        },
        {
          code: 'MP-024',
          description: 'Elástico Roliço 3mm Preto',
          unitId: units[0].id,
          value: 0.9,
          stock: 1000,
          supplierId: suppliers[1].id as unknown as number,
          colorId: colors[1].id,
          width: 0.003,
          locationId: locations[5].id,
          type: 'Aviamento',
          status: 'Ativo',
        },
        {
          code: 'MP-025',
          description: 'Linho Puro Off-White',
          unitId: units[0].id,
          value: 85.0,
          stock: 60,
          supplierId: suppliers[0].id as unknown as number,
          colorId: colors[14].id,
          width: 1.4,
          grammage: 180,
          locationId: locations[2].id,
          composition: '100% Linho',
          ncm: '5309.19.00',
          type: 'Tecido',
          status: 'Ativo',
          observation: 'Material premium - manuseio cuidadoso',
        },
      ]),
    );
    console.log(`✅ ${rawMaterials.length} matérias-primas criadas`);

    console.log('🌱 Seed concluído com sucesso!');
  }
}
